### ISSUE TITLE
Kurinto - Font

### ISSUE THREAD

**Issue by erdincay** [phax/ph-fonts#3]
Hi there!

Thank you for your project, this is awesome, but could you also add Kurinto https://kurinto.com/ to this project?

Thanks in advance.

Best regards!

**Comment by phax** [comment]
@erdincay  Thanks for bringing that font to my attention. I would add the "Sans" variant - is that okay for you?

**Comment by erdincay** [comment]
hi @phax, the Sans version is fine, but I assume some would also want the Mono variant too. thx for your quick response. br, Erdinc

**Comment by phax** [comment]
Will be part of the upcoming 5.0.2 release

**Comment by erdincay** [comment]
thx phax for this extremely professional support
